#!/bin/bash

mkdir -p /tmp/infofeld-$USER
pids=()
trap 'kill "${pids[@]}"' EXIT

(
    while true
    do
        infofeld-sun 150 $INFOFELD_HEIGHT >/tmp/infofeld-$USER/sun.new
        mv /tmp/infofeld-$USER/sun.{new,ff}
        sleep 10 || break
    done
) &
pids+=($!)

(
    while true
    do
        infofeld-memory 50 $INFOFELD_HEIGHT >/tmp/infofeld-$USER/memory.new
        mv /tmp/infofeld-$USER/memory.{new,ff}
        sleep 1 || break
    done
) &
pids+=($!)

(
    while true
    do
        infofeld-cpu 50 $INFOFELD_HEIGHT >/tmp/infofeld-$USER/cpu.new
        mv /tmp/infofeld-$USER/cpu.{new,ff}
        sleep 1 || break
    done
) &
pids+=($!)

(
    while true
    do
        infofeld-net 100 $INFOFELD_HEIGHT >/tmp/infofeld-$USER/net.new
        mv /tmp/infofeld-$USER/net.{new,ff}
        sleep 1 || break
    done
) &
pids+=($!)

(
    while true
    do
        infofeld-temperature 50 $INFOFELD_HEIGHT \
            >/tmp/infofeld-$USER/temperature.new
        mv /tmp/infofeld-$USER/temperature.{new,ff}
        sleep 1 || break
    done
) &
pids+=($!)

while sleep 1
do
    echo a
    echo i0/tmp/infofeld-$USER/cpu.ff
    echo -
    echo i0/tmp/infofeld-$USER/memory.ff
    echo -
    echo i0/tmp/infofeld-$USER/net.ff
    echo -
    echo i0/tmp/infofeld-$USER/temperature.ff
    echo -
    echo i0/tmp/infofeld-$USER/sun.ff
    echo e

    echo f
done
